Learning_Django/Learning_Django/urls.py
from django.contrib import admin
from django.urls import path, include
# from polls import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
]

Learning_Django/polls/urls.py
from django.urls import path 
from . import views

app_name = "polls"

urlpatterns = [
    #example: /polls/
    path("", views.IndexView.as_view(), name="index"),
    #example: /polls/1
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    #example: /polls/1/result
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    #example: /polls/1/vote
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

Learning_Django/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return f"{self.question_text}"

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.choice_text} : {self.votes}"
    

Learning_Django/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader 
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        # return Question.objects.order_by("-pub_date")[:5]
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    

def index(request):
    latest_question_list = Question.objects.order_by("pub_date")[:5]
    response = "/n".join(question.question_text for question in latest_question_list)

    template = loader.get_template("polls/index.html")
    context = {
        "latest_question_list" : latest_question_list,
    }


    # html_response = ""

    # for question in latest_question_list:
        # html_question_div = "<div>"
        # html_question_h3 = f"<h3>{question.question_text}</h3>"

        # html_choice_list = "<ul>"

        # for choice in question.choice_set.all():
        #     choice_li = f"<li>{choice.choice_text}</li>"
        #     html_choice_list = html_choice_list + choice_li 
        
        # html_choice_list = html_choice_list + "</ul>"
        
        # html_question_div = html_question_div + html_question_h3 + html_choice_list
        # html_question_div = html_question_div + "</div>"

        # html_response = html_response + html_question_div

    # return HttpResponse(template.render(context, request))
    return render(request, "polls/index.html" , context)


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
    


def detail(request, question_id):

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question Doesn't Exist.")

    question = get_object_or_404(Question, pk=question_id)

    context = {
        "question" : question,
    }

    # return HttpResponse(f"You're looking at question {question_id}.")
    return render(request, "polls/detail.html" , context)


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
    


def results(request, question_id):
    # response = f"You're looking at the results of question {question_id}."
    # return HttpResponse(response)

    question = get_object_or_404(Question, pk=question_id)

    context = {
        "question" : question,
    }
    return render(request, "polls/results.html", context) 


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        seleted_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        error_message = "You didn't vote."
        context = {
            "question" : question,
            "error_message" : error_message,
        }
        return render(request, "/polls/detail.html", context)

        # return HttpResponseRedirect(reverse("polls:detail", args=(question_id,)), context)

    seleted_choice.votes += 1
    seleted_choice.save()

    # return HttpResponse(f"You're voting on question {question_id}.")

    return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))

Learning_Django/polls/templates/polls/detail.html
{% comment %} {{question.question_text}}

<ul>
{% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}}</li>
{% endfor %}
</ul> {% endcomment %}


<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question.question_text}}</h1></legend>

        {% if error_message %}
            <script>alert("{{error_message|safe}}")</script>
            <p><strong>{{error_message}} {{re}}</strong></p>
        {% endif %}

        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
            <br>
        {% endfor %}
  
    </fieldset>

    <input type="submit" value="Vote!">

</form>

Learning_Django/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            {% comment %} <li><a href="/polls/{{question.id}}/">{{question.question_text}}</a></li> {% endcomment %}
            <li><a href= {% url 'polls:detail' question.id %} >{{question.question_text }}</a></li>
        {% endfor %}
    </ul>

{% else %}
    <h2>No poll to available. Come back later.</h2> 

{% endif %}

Learning_Django/polls/templates/polls/results.html
{{question.question_text}}

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} : {{choice.votes}} vote{{choice.votes|pluralize}} </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>